# PORTED FROM: PCSX2 macOS CMake — BionicSX2 iOS Port
# AUDIT REFERENCE: Phase 1 — iOS Toolchain File
# STATUS: NEW — iOS cross-compilation toolchain

set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET "16.0" CACHE STRING "" FORCE)
set(CMAKE_OSX_SYSROOT "iphoneos" CACHE STRING "" FORCE)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(PKG_CONFIG_EXECUTABLE "" CACHE FILEPATH "" FORCE)
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SOURCE_DIR}/ios-deps/install")
set(CMAKE_PREFIX_PATH "${CMAKE_SOURCE_DIR}/ios-deps/install" CACHE PATH "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
